### ISSUE TITLE
Copy button doesn't copy values correctly

### ISSUE THREAD

**Issue by pawarsoham008** [omkartapale/country-codes#14]
Copy to Clipboard button doesn't work when country names copy + pasted into the search. 

To regenerate the issue try copying and pasting country names into the search one after another and click on Copy to Clipboard button from the search result.

In my opinion, this is caused due to updated value not being passed to the Clipboard and returning an old copied value.

App Version: 0.1.0
Browser: Chrome 112

**Comment by omkartapale** [comment]
Thank you @pawarsoham008 for highlighting this. We'll fix it soon
