### ISSUE TITLE
Search input should be trimmed before search operation

### ISSUE THREAD

**Issue by pawarsoham008** [omkartapale/country-codes#16]
Search input text should be trimmed before the search operation on the Lookup screen.

To regenerate the issue try adding space before or after of text inputted in the search field.

App Version: 0.1.1
Browser: Chrome 112

**Comment by pawarsoham008** [comment]
Thank you @pawarsoham008 for highlighting this. This is resolved now

**Comment by omkartapale** [comment]
Thank you @pawarsoham008 for highlighting this. This is resolved now
